name: Build Howl

on:
  workflow_dispatch:
  push:
    branches: [ alpha ]


jobs:
  apk:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Restore Gradle cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-grad

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/debug.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/HowlMusic-debug.apk

      - name: Send APK
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: New HowlMusic Build
          document: app/build/outputs/apk/debug/HowlMusic-debug.apk

      - name: Send Changelog
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ github.event.head_commit.message }}