name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ alpha ]

jobs:
  apk:

    name: Build on Ubuntu
    runs-on: ubuntu-latest
    env:
      NDK_CCACHE: ${{ github.workspace }}/ccache
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up ccache
        run: bash .github/ccache.sh

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.ccache
            ~/.gradle/caches/build-cache-*
            key: ${{ runner.os }}-build-cache-${{ github.sha }}
            restore-keys: ${{ runner.os }}-build-cache-

      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Stop Gradle daemon
        run: ./gradlew --stop

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/HowlMusic-debug.apk

      - name: Send APK
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: New HowlMusic Build
          document: app/build/outputs/apk/debug/HowlMusic-debug.apk

      - name: Send Changelog
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ github.event.head_commit.message }}
